Labb1/Models/CustomerBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Labb1.Models
{
    public class CustomerBook
    {
        public int CustomerBookId { get; set; }
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }
        public int BookId { get; set; }
        public Book Book { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yy}")]
        public DateTime LoanDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yy}")]
        public DateTime ReturnDate { get; set; }
    }
}

Labb1/ViewModels/CustomerBooksViewModel.cs
using Labb1.Models;
using System.Collections.Generic;

namespace Labb1.ViewModels
{
    public class CustomerBooksViewModel
    {
        public IEnumerable<CustomerBook> CustomerBook { get; set; }
        public IEnumerable<Book> Books { get; set; }
        public Customer customers { get; set; }
        //public IEnumerable<Customer> Customers { get; set; }
    }
}

Labb1/Controllers/BookController.cs
using Labb1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Labb1.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;


        public BookController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public IActionResult Index()
        {
            return View(_bookRepository.GetAllBooks.ToList());
        }
    }
}

Labb1/Controllers/CustomerBookController.cs
using Labb1.Models;
using Labb1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Net;
using static System.Reflection.Metadata.BlobBuilder;

namespace Labb1.Controllers
{
    public class CustomerBookController : Controller
    {


        private readonly AppDbContext _appDbContext;
        public CustomerBookController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Loan(int id)
        {

            var customer = _appDbContext.Customers.FirstOrDefault(i => i.CustomerId ==id);
            IEnumerable<CustomerBook> customerBooks = _appDbContext.CustomerBooks.Where(f => f.CustomerId ==id).ToList();
            IEnumerable<Book> books = _appDbContext.Books.ToList();

            var CustomerBooksViewModel = new CustomerBooksViewModel
            {
                customers = customer,
                CustomerBook = customerBooks,
                Books = books
            };
            return View(CustomerBooksViewModel);


        }

        public IActionResult Create(int id)
        {
            var customerBook = new CustomerBook()
            {
                BookId = id
            };
            IEnumerable<Customer> customers = _appDbContext.Customers.ToList();

            var CustomerViewModel = new CustomerViewModel()
            {
                customers = customers,
                CustomerBook = customerBook,
            };

            return View(CustomerViewModel);
        }
        [HttpPost]
        public IActionResult Create(CustomerViewModel CustomerViewModel)
        {
            var loanDate = CustomerViewModel.CustomerBook.LoanDate=DateTime.Now;
            CustomerViewModel.CustomerBook.ReturnDate= loanDate.AddDays(30);
            _appDbContext.Add(CustomerViewModel.CustomerBook);
            _appDbContext.SaveChanges();

            return View("Checkouted");
        }
    }
}

Labb1/Views/CustomerBook/Checkouted.cshtml
<h1>Checkout Completed</h1>

<div class="col-md-6">
    <a asp-controller="Book" asp-action="Index" class="btn btn-secondary w-100">Se alla böcker</a>
</div>

Labb1/Views/CustomerBook/Create.cshtml
@model CustomerViewModel

<div class="row">
    <div class="col-md-6 offset-1-md-3">
        <h3>Ange LåneID</h3>
        <form asp-controller="CustomerBook" asp-action="Create" autocomplete="on">
            <input type="hidden" asp-for="CustomerBook.CustomerBookId" />
            <input type="hidden" asp-for="CustomerBook.LoanDate" />
            <input type="hidden" asp-for="CustomerBook.ReturnDate" />
            <input type="hidden" asp-for="CustomerBook.BookId" />

            <div class="form-group">
            <label >Välj Låntagare</label>
            <select asp-for="@Model.CustomerBook.CustomerId" class="form-select form-select-lg" aria-label=".form-select-lg">
            @foreach (var item in Model.customers)
            {
                <option value="@item.CustomerId">@item.FirstName @item.LastName </option>
            }
            </select>
            </div>
            <div class="row mt-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="submit" value="submit" class="btn btn-primary w-100" />
                    </div>
                </div>
                <div class="col-md-6">
                    <a asp-controller="Book" asp-action="Index" class="btn btn-secondary w-100">Se alla böcker</a>
                </div>
            </div>
        </form>
    </div>
</div>

Labb1/Views/CustomerBook/Loan.cshtml
@using Labb1.ViewModels

@model CustomerBooksViewModel

<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Author
        </th>
        <th>
            Returned
        </th>
        <th>
            Images
        </th>
        <th>
            Återlämmnings Datum
        </th>
    </tr>


@foreach (var item in Model.CustomerBook)
{
    var test = Model.Books.Where(i => i.BookId ==item.BookId);
    @foreach (var items in test)
    {
            <tbody>
                <tr>
                    <td>
                        @items.Title
                    </td>

                    <td>
                        @items.Author
                    </td>
               <td>
                        @if (items.Avalible)
                        {
                            <p>Boken är återlämnad</p>
                        }
                        @if (!items.Avalible)
                        {
                            <p>Boken är inte återlämnad</p>
                        }
               </td>
               <td>
                        <img src="@items.ImageUrl" class="img-fluid">
               </td>
               
                <td>
                        <p>@item.ReturnDate </p>
                </td>
                

                </tr>
            </tbody>
     

       
    }
}
</table>